// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wszzzivthjvgzypseryl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indzenp6aXZ0aGp2Z3p5cHNlcnlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzE4MTIsImV4cCI6MjA2Nzc0NzgxMn0.Bwy6asiU0ET1IeNFA5FpHA_SWX3le83eld0XR1LaZ7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});